home/urls.py
from django.urls import path

from . import views
app_name ='home'#uygulamanın adını path ile çağırmak için
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_form),
    path('join', views.join_form),
    path('logout', views.login_out),
    path('panel/<int:id>', views.panel),
    path('contact', views.contact_form, name='contact'),



]

order/urls.py
from django.urls import path

from . import views
app_name ='order'#uygulamanın adını path ile çağırmak için
urlpatterns = [
    path('', views.index, name='index'),
    path('shopcart', views.shop_cart_list, name='shopcart'),
    path('addtocart/<int:proid>', views.shop_cart_add, name='addtocart'),
    path('deletefromcart/<int:id>', views.shop_cart_delete, name='deletefromcart'),
    path('checkout', views.shop_cart_checkout, name='checkout'),
    path('detail/<int:id>', views.order_detail, name='orderdetail'),



    # ex: /polls/5/results/
   # path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
  #  path('<int:question_id>/vote/', views.vote, name='vote'),
]

yazproje/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from yazproje import settings

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from typing import List

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import TextInput, ModelForm

from product.models import Product


class Shopcart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product

    @property
    def amount(self):
        return (self.quantity * self.product.price)


class ShopCartForm(ModelForm):
    class Meta:
        model = Shopcart
        fields = ['quantity']
        widgets = {
            'quantity': TextInput(attrs={'class': 'input', 'type': 'number', 'value': '1', 'placeholder': 'adet'}),

        }


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('Onshipping', 'Onshipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    surname = models.CharField(max_length=10)
    address = models.CharField(max_length=10)
    city = models.CharField(max_length=10)
    phone = models.CharField(max_length=10)
    total = models.FloatField()
    note = models.TextField(null=True, default="")
    status = models.CharField(choices=STATUS, default='New', max_length=15)
    creatat = models.DateTimeField(auto_now_add=True)
    updateat = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'surname', 'address', 'city', 'phone']
        widgets = {

            'name': TextInput(attrs={'class': 'input', 'type': 'text', }),
            'surname': TextInput(attrs={'class': 'input', 'type': 'text', }),
            'address': TextInput(attrs={'class': 'input', 'type': 'text', }),
            'city': TextInput(attrs={'class': 'input', 'type': 'text', }),
            'phone': TextInput(attrs={'class': 'input', 'type': 'text', }),


        }


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    total = models.FloatField()
    creatat = models.DateTimeField(auto_now_add=True)
    updateat = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.
from django.urls import reverse
from django.forms import ModelForm
from django.shortcuts import render, redirect
from order.models import ShopCartForm, Shopcart, OrderForm, Order, OrderDetail


@login_required(login_url='/login')
def index(request):
    current_user = request.user
    orders = Order.objects.all().filter(user_id=current_user.id)
    context = {
        'page': 'orders',
        'orders': orders,
    }

    return render(request, 'order_list.html', context)


@login_required(login_url='/login')
def shop_cart_list(request):

    current_user = request.user
    shopcart = Shopcart.objects.all().filter(user_id=current_user.id)
    carttotal=0

    for rs in shopcart:
        carttotal+=rs.quantity * rs.product.price
    context = {'page': 'cart',
               'shopcart': shopcart,
               'carttotal': carttotal,

               }
    return render(request, 'shop_cart_list.html', context)


@login_required(login_url='/login')
def shop_cart_add(request, proid):
    url1 = "/product/"+str(proid)+"/"
    url = request.META.get('HTTP_REFERER')
    form = ShopCartForm(request.POST or None)
    if request.method == 'POST':

        if form.is_valid():
            current_user = request.user
            quantity = form.cleaned_data['quantity']
            try:
                q1 = Shopcart.objects.get(user_id=current_user.id, product_id=proid)
            except Shopcart.DoesNotExist:
                q1 = None
            if q1 != None:
                q1.quantity = q1.quantity + quantity
                q1.save()
            else:
                data = Shopcart(user_id=current_user.id, product_id=proid, quantity=quantity)
                data.save()
            request.session['cart_items'] = Shopcart.objects.filter(user_id=current_user.id).count()
            messages.success(request, "product add to cart")
            return HttpResponseRedirect(url)

    return HttpResponseRedirect(url1)


@login_required(login_url='/login')
def shop_cart_delete(request, id):
    url = request.META.get('HTTP_REFERER')
    Shopcart.objects.filter(id=id).delete()
    messages.success(request, "Product deleted from cart")
    return HttpResponseRedirect(url)


@login_required(login_url='/login')
def shop_cart_checkout(request):
    current_user = request.user
    shopcart = Shopcart.objects.all().filter(user_id=current_user.id)
    carttotal=0
    for rs in shopcart:
        carttotal+=rs.quantity * rs.product.price

    form = OrderForm(request.POST or None)
    if request.method == 'POST':

        if form.is_valid():
            data = Order()
            data.name = form.cleaned_data['name']
            data.surname = form.cleaned_data['surname']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = carttotal
            data.save()

            for rs in shopcart:
                detail = OrderDetail()
                detail.order_id = data.id
                detail.product_id = rs.product_id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity
                detail.price = rs.product.price
                detail.total = rs.amount
                detail.save()
            Shopcart.objects.filter(user_id=current_user.id).delete()
            request.session['cart_item'] = 0
            messages.success(request, "Order has been completed Thank you")
            return HttpResponseRedirect("/order")

    context = {
        'page': 'checkout',
        'shopcart': shopcart,
        'carttotal': carttotal,
    }
    return render(request, 'shop_cart_checkout.html', context)


@login_required(login_url='/login')
def order_detail(request, id):
    order = Order.objects.get(pk=id)
    items = OrderDetail.objects.all().filter(order=id)
    context = {
        'page': 'detail',
        'order': order,
        'items': items,
    }
    return render(request, 'order_detail.html', context)

order/templates/order_detail.html
{% extends "homebase.html" %}

{% block title %} Orders Detay  {% endblock %}

{% block sidebar %} {% include "usermenu.html" %} {% endblock %}

{% block content   %}
    <div class="w3l_banner_nav_right">
        <!-- about -->
        <div class="privacy about">
            <h1>Orders Detay</h1>

            <table class="table">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ order.id }}</td>
                </tr>
                <tr>
                    <th>Userid</th>
                    <td>{{ order.user }}</td>
                </tr>
                <tr>
                    <th>Amount</th>
                    <td>{{ order.total }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ order.name }}</td>
                </tr>
                <tr>
                    <th>Adress</th>
                    <td>{{ order.address }}</td>
                </tr>
                <tr>
                    <th>City</th>
                    <td>{{ order.city }}</td>
                </tr>
                <tr>
                    <th>Phone</th>
                    <td>{{ order.phone }}</td>
                </tr>



                </tbody>
            </table>
            <table class="table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Product Name</th>
                    <th>Sale Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
                </thead>
                {% for rs in items %}
                    <tr>
                        <td>{{ rs.id }}</td>
                        <td>{{ rs.product.title }}</td>
                        <td>{{ rs.price }}</td>
                        <td>{{ rs.quantity }}</td>
                        <td>{{ rs.total }}</td>
                    <tr>
                {% endfor %}
                <tr><td colspan="5">Toplam Alışveriş Tutarı: {{ order.total }} TL<br></td> </tr>
                </tbody>
            </table>

        </div>

    </div>
    <div class="clearfix">

    </div>



{% endblock %}

order/templates/order_list.html
{% extends "homebase.html" %}

{% block title %} shop cart  {% endblock %}

{% block sidebar %} {% include "usermenu.html" %} {% endblock %}

{% block content   %}


<div class="w3l_banner_nav_right">
    <!-- about -->
    <div class="privacy about">
    <h1>Orders index</h1>
{% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
                {% endfor %}

            {% endif %}
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Userid</th>
                <th>Amount</th>
                <th>Name</th>
                <th>Adres</th>
                <th>City</th>
                <th>Phone</th>
                <th>Status</th>
                <th>Note</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.user }}</td>
                <td>{{ order.total }}</td>
                <td>{{ order.name }}</td>
                <td>{{ order.address }}</td>
                <td>{{ order.city }}</td>
                <td>{{ order.phone }}</td>
                <td>{{ order.status }}</td>
                <td>{{ order.note }}</td>

                <td>
                    <a href="/order/detail/{{ order.id }}"class="btn btn-block btn-warning btn-xs">show</a>

                </td>

            </tr>


        {% endfor %}
        </tbody>
    </table>



    </div>
    <!-- //about -->
</div>
    <div class="clearfix"></div>
    </div>
    <!-- //banner -->
    <!-- team -->

{% endblock %}

order/templates/shop_cart_checkout.html
{% extends "homebase.html" %}
{% load static %}
{% block title %} Spariş {% endblock %}
{% block content %}
   <div class="mail">
        <h3> Spariş Tablosu  </h3>
        <div class="agileinfo_mail_grids">
            <div class="col-md-8 agileinfo_mail_grid_right">
                <div class="row form-group">
                            <div class="col col-sm-3">
                                <label for="input-normal" class=" form-control-label">Toplam Tutar</label>
                            </div>
                            <div class="col col-sm-6">
                                <input class="input" type="text" name="name" value="{{carttotal}}"  id="id_name">
                            </div>
                        </div>



                <form  action="/order/checkout"  method="post" >
                    {% csrf_token %}
                    <div class="row form-group">
                            <div class="col col-sm-3">
                                <label for="input-normal" class=" form-control-label">Adı</label>
                            </div>
                            <div class="col col-sm-6">
                                <input class="input" type="text" name="name" value="{{user.username}}"  id="id_name">
                            </div>
                        </div>


                    <div class="row form-group">
                            <div class="col col-sm-3">
                                <label for="input-normal" class=" form-control-label">Soyadı</label>
                            </div>
                            <div class="col col-sm-6">
                                <input class="input"type="text" name="surname"  id="id_surname">
                            </div>
                        </div>
                    <div class="row form-group">
                            <div class="col col-sm-3">
                                <label for="input-normal" class=" form-control-label">Adres</label>
                            </div>
                            <div class="col col-sm-6">
                                <textarea class="input" type="text" name="address"  id="id_address"></textarea>
                            </div>
                        </div>
                      <div class="row form-group">
                            <div class="col col-sm-3">
                                <label for="input-normal" class=" form-control-label">Telefon</label>
                            </div>
                            <div class="col col-sm-6">
                                <input class="input" type="text" name="phone"id="id_phone" >
                            </div>
                        </div>

                 <div class="row form-group">
                            <div class="col col-sm-3">
                                <label for="input-normal" class=" form-control-label">Şehir</label>

</div>
                            <div class="col col-sm-6">
                                <select class="input" type="text" name="city" id="id_city" >
                                    <option value="{{ user.city }}">{{ user.city }}</option>
                                    <option value="İstanbul">İstanbul</option>
                                    <option value="Ankara">Ankara</option>
                                    <option value="İzmir">İzmir</option>
                                    <option value="Adana">Adana</option>
                                    <option value="Adıyaman">Adıyaman</option>
                                    <option value="Afyonkarahisar">Afyonkarahisar</option>
                                    <option value="Ağrı">Ağrı</option>
                                    <option value="Aksaray">Aksaray</option>
                                    <option value="Amasya">Amasya</option>
                                    <option value="Antalya">Antalya</option>
                                    <option value="Ardahan">Ardahan</option>
                                    <option value="Artvin">Artvin</option>
                                    <option value="Aydın">Aydın</option>
                                    <option value="Balıkesir">Balıkesir</option>
                                    <option value="Bartın">Bartın</option>
                                    <option value="Batman">Batman</option>
                                    <option value="Bayburt">Bayburt</option>
                                    <option value="Bilecik">Bilecik</option>
                                    <option value="Bingöl">Bingöl</option>
                                    <option value="Bitlis">Bitlis</option>
                                    <option value="Bolu">Bolu</option>
                                    <option value="Burdur">Burdur</option>
                                    <option value="Bursa">Bursa</option>
                                    <option value="Çanakkale">Çanakkale</option>
                                    <option value="Çankırı">Çankırı</option>
                                    <option value="Çorum">Çorum</option>
                                    <option value="Denizli">Denizli</option>
                                    <option value="Diyarbakır">Diyarbakır</option>
                                    <option value="Düzce">Düzce</option>
                                    <option value="Edirne">Edirne</option>
                                    <option value="Elazığ">Elazığ</option>
                                    <option value="Erzincan">Erzincan</option>
                                    <option value="Erzurum">Erzurum</option>
                                    <option value="Eskişehir">Eskişehir</option>
                                    <option value="Gaziantep">Gaziantep</option>
                                    <option value="Giresun">Giresun</option>
                                    <option value="Gümüşhane">Gümüşhane</option>
                                    <option value="Hakkâri">Hakkâri</option>
                                    <option value="Hatay">Hatay</option>
                                    <option value="Iğdır">Iğdır</option>
                                    <option value="Isparta">Isparta</option>
                                    <option value="Kahramanmaraş">Kahramanmaraş</option>
                                    <option value="Karabük">Karabük</option>
                                    <option value="Karaman">Karaman</option>
                                    <option value="Kars">Kars</option>
                                    <option value="Kastamonu">Kastamonu</option>
                                    <option value="Kayseri">Kayseri</option>
                                    <option value="Kırıkkale">Kırıkkale</option>
                                    <option value="Kırklareli">Kırklareli</option>
                                    <option value="Kırşehir">Kırşehir</option>
                                    <option value="Kilis">Kilis</option>
                                    <option value="Kocaeli">Kocaeli</option>
                                    <option value="Konya">Konya</option>
                                    <option value="Kütahya">Kütahya</option>
                                    <option value="Malatya">Malatya</option>
                                    <option value="Manisa">Manisa</option>
                                    <option value="Mardin">Mardin</option>
                                    <option value="Mersin">Mersin</option>
                                    <option value="Muğla">Muğla</option>
                                    <option value="Muş">Muş</option>
                                    <option value="Nevşehir">Nevşehir</option>
                                    <option value="Niğde">Niğde</option>
                                    <option value="Ordu">Ordu</option>
                                    <option value="Osmaniye">Osmaniye</option>
                                    <option value="Rize">Rize</option>
                                    <option value="Sakarya">Sakarya</option>
                                    <option value="Samsun">Samsun</option>
                                    <option value="Siirt">Siirt</option>
                                    <option value="Sinop">Sinop</option>
                                    <option value="Sivas">Sivas</option>
                                    <option value="Şırnak">Şırnak</option>
                                    <option value="Tekirdağ">Tekirdağ</option>
                                    <option value="Tokat">Tokat</option>
                                    <option value="Trabzon">Trabzon</option>
                                    <option value="Tunceli">Tunceli</option>
                                    <option value="Şanlıurfa">Şanlıurfa</option>
                                    <option value="Uşak">Uşak</option>
                                    <option value="Van">Van</option>
                                    <option value="Yalova">Yalova</option>
                                    <option value="Yozgat">Yozgat</option>
                                    <option value="Zonguldak">Zonguldak</option>
                                </select>
                                  </div>
                        </div>
                    <input type="submit" value="send form">
                </form>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
{% endblock %}

order/templates/shop_cart_list.html
{% extends "homebase.html" %}

{% block title %} shop cart  {% endblock %}

{% block sidebar %} {% include "usermenu.html" %} {% endblock %}

{% block content   %}

<div class="w3l_banner_nav_right">
    <!-- about -->
    <div class="privacy about">

        <div class="w3l_banner_nav_right">

            <div class="agileinfo_single">


    <h1>Shopcart Listesi</h1>

            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
                {% endfor %}

            {% endif %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Product Name</th>
                <th>Sale Price</th>
                <th>Quantity</th>
                <th>Amount</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>


        {% for shopcart in shopcart %}
            <tr>
                <td>{{ shopcart.id }}</td>
                <td>{{ shopcart.product.title }}</td>
                <td>{{ shopcart.product.price }}</td>
                <td>{{ shopcart.quantity }}</td>
                <td>{{ shopcart.amount }} TL</td>
                <td>
                    <a href="/order/deletefromcart/{{ shopcart.id }}" class="btn btn-block btn-warning btn-xs">sil</a>
                </td>
            </tr>
        {% endfor %}
        <td colspan="5" ><b> toplam alışveriş tutarı :{{ carttotal }} TL</b>
            <td>
        <a href="/order/checkout"  class="btn btn-block btn-danger btn-xs" >satın al</a>
</td>
        </tbody>
    </table>



            </div>
        </div>
    </div>
</div>
    </div>
    <div class="clearfix">
    </div>
    </div>

    </div>
    <!-- //about -->
    </div>
    <div class="clearfix"></div>
    </div>
    <!-- //banner -->
    <!-- team -->

{% endblock %}